dev:
  1: mailer.dev.naukri.com
  2: mailer.dev.naukrigulf.com
  3: mailer.dev.firstnaukri.com

test:
  1: mailer.test.naukri.com
  2: mailer.test.naukrigulf.com
  3: mailer.test.firstnaukri.com

live:
  1: mailer.naukri.com
  2: mailer.naukrigulf.com
  3: mailer.firstnaukri.com
